version: 0.1.{build}
image: Visual Studio 2022
configuration: Release
environment:
  DEPLOY_URL:
    secure: tI50+kR1mSDCXK8B4BPyT9ArtYD3D1NAvb5/06G8mFA=  
  DEPLOY_USER:
    secure: IZcgg6msojQGCM0rLsUNTA==
  DEPLOY_KEY:
    secure: SXvCUsowLsFFH1P7e3IsqldBlcPD0gQ8qpsSM8s73VUImWk+NW0dbnLjbytCriqD6O3+FiBLKWkE/v0bNckEJkwFDU8y2ZuNjmB2NIyAQViPyi72/a3vRPM7ruJH+BY0
  REPO_TOKEN:
      secure: 0qeEEToZuwVcvYxnrAA5DeRQmdRMeYmrtmJKGUVFeTFteeMrw4z6pPUEE3wley1p
init:
  - ps: Start-Service MySQL80
install:
- cmd: git submodule update --init --recursive
before_build:
- ps: (Get-Content WoWDatabaseEditorCore.Avalonia/Services/ProgramNameService.cs) -replace 'Subtitle => ""', 'Subtitle => "for open source emulator use"' | Out-File -encoding UTF8 WoWDatabaseEditorCore.Avalonia/Services/ProgramNameService.cs
build_script:
- cmd: bash.exe build.sh
test_script:
- cmd: >-
    cd test
    
    bash database_test.sh localhost 3306 root 'Password12!' 'C:\Program Files\MySQL\MySQL Server 8.0\bin\mysql'

    cd ../

    dotnet test WDE.MVVM.Test/WDE.MVVM.Test.csproj

    dotnet test WDE.RemoteSOAP.Test/WDE.RemoteSOAP.Test.csproj

    dotnet test WDE.SmartScriptEditor.Test/WDE.SmartScriptEditor.Test.csproj

    dotnet test WDE.Updater.Test/WDE.Updater.Test.csproj

    dotnet test WDE.Parameters.Test/WDE.Parameters.Test.csproj

    dotnet test WDE.SqlQueryGenerator.Test/WDE.SqlQueryGenerator.Test.csproj

    dotnet test WDE.SqlInterpreter.Test/WDE.SqlInterpreter.Test.csproj

    dotnet test WDE.Common.Test/WDE.Common.Test.csproj
      
    dotnet test Modules/WDE.SqlWorkbench.Test/WDE.SqlWorkbench.Test.csproj

    dotnet test Rendering/TheEngine.Test/TheEngine.Test.csproj

    dotnet test WDE.WoWHeadConnector.Test/WDE.WoWHeadConnector.Test.csproj

    dotnet test WoWDatabaseEditorCore.Test/WoWDatabaseEditorCore.Test.csproj
      
    dotnet test Modules/WDE.DatabaseEditors.Test/WDE.DatabaseEditors.Test.csproj
      
    dotnet test Modules/WDE.Debugger.Test/WDE.Debugger.Test.csproj
      
    Rem dotnet test Modules/WDE.PacketViewer.Test/WDE.PacketViewer.Test.csproj
artifacts:
- path: WoWDatabaseEditorMacOs.zip
  name: WoWDatabaseEditorMacOs.zip
- path: WoWDatabaseEditorWindows.zip
  name: WoWDatabaseEditorWindows.zip
- path: WoWDatabaseEditorLinux.zip
  name: WoWDatabaseEditorLinux.zip
deploy_script:
- cmd: >-
    IF NOT "%DEPLOY_KEY%" == "" curl -X POST "%DEPLOY_URL%/Upload" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "branch=%APPVEYOR_REPO_BRANCH%" -F "marketplace=default" -F "platform=windows" -F "version=%APPVEYOR_BUILD_NUMBER%" -F "versionName=Build %APPVEYOR_BUILD_VERSION%" -F "user=%DEPLOY_USER%" -F "key=%DEPLOY_KEY%" -F "files=@WoWDatabaseEditorWindows.zip;type=application/zip"
    
    IF NOT "%DEPLOY_KEY%" == "" curl -X POST "%DEPLOY_URL%/Upload" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "branch=%APPVEYOR_REPO_BRANCH%" -F "marketplace=default" -F "platform=macos" -F "version=%APPVEYOR_BUILD_NUMBER%" -F "versionName=Build %APPVEYOR_BUILD_VERSION%" -F "user=%DEPLOY_USER%" -F "key=%DEPLOY_KEY%" -F "files=@WoWDatabaseEditorMacOs.zip;type=application/zip" -F "make_exec=WoW Database Editor.app/Contents/MacOS/WoWDatabaseEditorCore.Avalonia"
    
    IF NOT "%DEPLOY_KEY%" == "" curl -X POST "%DEPLOY_URL%/Upload" -H "accept: */*" -H "Content-Type: multipart/form-data" -F "branch=%APPVEYOR_REPO_BRANCH%" -F "marketplace=default" -F "platform=linux" -F "version=%APPVEYOR_BUILD_NUMBER%" -F "versionName=Build %APPVEYOR_BUILD_VERSION%" -F "user=%DEPLOY_USER%" -F "key=%DEPLOY_KEY%" -F "files=@WoWDatabaseEditorLinux.zip;type=application/zip" -F "make_exec=WoWDatabaseEditorCore.Avalonia" -F "make_exec=_Updater" -F "make_exec=parser/WowPacketParser"
    
    IF NOT "%DEPLOY_KEY%" == "" curl -X POST "%DEPLOY_URL%/Changelog/Add" -H  "accept: */*" -H  "Content-Type: application/json" -d "{\"version\":{\"branch\":\"%APPVEYOR_REPO_BRANCH%\",\"marketplace\":\"default\",\"version\":%APPVEYOR_BUILD_NUMBER%},\"user\":{\"user\":\"%DEPLOY_USER%\",\"key\":\"%DEPLOY_KEY%\"},\"entry\":\"%APPVEYOR_REPO_COMMIT_MESSAGE%%APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED%\"}"
